# Generated by Django 3.0.6 on 2020-05-19 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=200, unique=True)),
                ('ten_lop', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sinhvien',
            options={'verbose_name': 'Sinh Viên', 'verbose_name_plural': 'Sinh Viên'},
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='gioi_tinh',
            field=models.BooleanField(default=False, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='ho_ten',
            field=models.CharField(default='', max_length=200, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='masv',
            field=models.CharField(max_length=200, unique=True, verbose_name='Mã sinh viên'),
        ),
        migrations.CreateModel(
            name='SinhVienLopHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gio_hoc', models.IntegerField(default=7)),
                ('lop_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.LopHoc')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.SinhVien')),
            ],
        ),
    ]
