# Generated by Django 3.0.6 on 2020-05-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200519_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ten_mon', models.CharField(max_length=255)),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.LopHoc')),
            ],
        ),
    ]
